SELECT * FROM REQID_DETAILS('R2');

SELECT * FROM CUSTOMER_DETAILS('Alex');

SELECT * FROM TASK_OVERTIME_TNO('T1');

SELECT * FROM TASK_OVERTIME_ENAME('E13');

SELECT * FROM TASK_OVERTIME_SEL('Name', 'Emma');

SELECT * FROM TASK_EMP('E13');

SELECT * FROM SEARCH_EMPLOYEE('E1');

SELECT * FROM SEARCH_MANAGER('E10');

SELECT * FROM SEARCH_COMPANY('CO1');

SELECT * FROM GET_PROJECTS_IN_COMPANY('CO1');